# This file is a template, and might need editing before it works on your project.
image: spork.spawar.navy.mil/bblaine/csa-tools-image/csa-tools-image:latest

cache:
  paths:
    - node_modules

stages:
  - build  # dummy stage to follow the template guidelines
  - test
  - deploy  # dummy stage to follow the template guidelines
  - review
  - staging
  - production
  - cleanup

variables:
  OPENSHIFT_SERVER: ocp.csa.spawar.navy.mil
  # OPENSHIFT_DOMAIN: apps.example.com
  # Configure this variable in Secure Variables:
  OPENSHIFT_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJiYmxhaW5lLXNhbmRib3giLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZGVwbG95ZXItdG9rZW4tOW5zeGciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVwbG95ZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIyOTYxOGIxYy0zMzJmLTExZWEtODczMS0wMjJhYTEzMjA1YTAiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6YmJsYWluZS1zYW5kYm94OmRlcGxveWVyIn0.ptDhhyh5WOdgBmiylFjtTYulL2A74UxxkmSpNdOvp039VlkRBOJODh4VMqCtgtoEZl4FKqEXjqzfcxkgWjoNpO20Y5PYvksvecMH8-9Yx3k0PNaoepgrKsq5GbWDKKA7nurKTS3utzRx_6ivswhSq6IrLFXO7_hZU3eZ17Wdw9h1-4wB-xyYnGlAetr-eJU8P22Y3wy7kPzGOYdtoUOXuutqDUpWjNZC9q3Dd3Qa5hv2HKK53NboINSLUZIfs9BSWpKj0hBT69ofg1ZCLioRqF9Y8yRfieZSKoqCbiuT1prXG_ClcBThJdVXT665GYMJcKQ8dIoTB4eH24TnichTeg
  
compile:
  image: node:current
  stage: build
  before_script: []
  script:
    - npm install
    - npm run build

test:
  image: node:current
  stage: test
  before_script: []
  allow_failure: true
  script:
    - export CI=true
    - npm test

.deploy: &deploy
  image: spork.spawar.navy.mil/bblaine/csa-tools-image/csa-tools-image:latest
  before_script:
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
    - oc project "$CI_PROJECT_NAME-$CI_PROJECT_ID" 2> /dev/null || oc new-project "$CI_PROJECT_NAME-$CI_PROJECT_ID"
  script:
    - "oc get services $APP 2> /dev/null || oc new-app . --name=$APP --strategy=docker"
    - "oc start-build $APP --from-dir=. --follow || sleep 3s && oc start-build $APP --from-dir=. --follow"
    - "oc get routes $APP 2> /dev/null || oc expose service $APP --hostname=$APP_HOST"

review:
  image: spork.spawar.navy.mil/bblaine/csa-tools-image/csa-tools-image:latest
  <<: *deploy
  stage: review
  variables:
    APP: review-$CI_COMMIT_REF_NAME
    APP_HOST: $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$OPENSHIFT_DOMAIN
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$OPENSHIFT_DOMAIN
    on_stop: stop-review
  only:
    - branches
  except:
    - master

stop-review:
  image: spork.spawar.navy.mil/bblaine/csa-tools-image/csa-tools-image:latest
  <<: *deploy
  stage: cleanup
  script:
    - oc delete all -l "app=$APP"
  when: manual
  variables:
    APP: review-$CI_COMMIT_REF_NAME
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - branches
  except:
    - master

staging:
  image: spork.spawar.navy.mil/bblaine/csa-tools-image/csa-tools-image:latest
  <<: *deploy
  stage: staging
  variables:
    APP: staging
    APP_HOST: $CI_PROJECT_NAME-staging.$OPENSHIFT_DOMAIN
  environment:
    name: staging
    url: http://$CI_PROJECT_NAME-staging.$OPENSHIFT_DOMAIN
  only:
    - master

production:
  image: spork.spawar.navy.mil/bblaine/csa-tools-image/csa-tools-image:latest
  <<: *deploy
  stage: production
  variables:
    APP: production
    APP_HOST: $CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
  when: manual
  environment:
    name: production
    url: http://$CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
  only:
    - master
